### ISSUE TITLE
第二回WoTハンズオンに向けての問題点

### ISSUE THREAD

**Issue by KazukoShikiya** [KazukoShikiya/RaspPi_PWM_HandsOn#1]
RaspPi2の場合、ビルドしないとNode.jsのインストールができない。

同じコマンドでビルドするとRaspPi Bでは以下URLと同じ問題が発生する。
https://github.com/joyent/node/issues/9163
./configure --without-snapshotで実験中

**Comment by KazukoShikiya** [comment]
##### Raspberry Pi 2の場合の方法（案）

nodebrewは使わず、
Node.jsは、ソースコードからビルドする
wget http://nodejs.org/dist/v0.12.7/node-v0.12.7.tar.gz
tar xvf node-v0.12.7.tar.gz
cd node-v0.12.7
./configure
make
sudo make install

インストールできたか確認のため、バージョン表示してみる
コマンド：
node -v
npm -v

インストール先は、
/user/local/bin/node
/user/local/bin/npm
になっている

##### ここまでRaspberry Pi 2の場合の方法（案）

この方法もあるけれど、これだとＢ系は、snapshotのところで落ちる。
バージョン検討が面倒なので、いったん候補から外す。

**Comment by KazukoShikiya** [comment]
RPi2対策は後回し。

**Comment by come25136** [comment]
はじめまして、

> これだとＢ系は、snapshotのところで落ちる。

snapshotが見当たらないのですがどうすればいいのでしょうが。

**Comment by KazukoShikiya** [comment]
To @homebox25136 

書き込みいただいた内容の解釈ができなかったので、補足説明いただけますか？

書き込みを読んで、こちらで思い浮かんだ状況が、
1. このissueにある手順でNode.jsのインストールをBまたはB+で行ったが、snapshotのエラーログが出なかった
2. このissueにある手順でNode.jsのインストールをBまたはB+で行ったが、snapshotのインストール完了ログが出なかった
3. このissueにある手順でNode.jsのインストールを2で行ったが、snapshotのインストール完了ログが出なかった

…と、３つ浮かびました。
書き込みいただいた内容の解釈で、@homebox25136さんの意図は、このうちの何番でしょうか。
お手数ですが、お答えください。

なお、このissueは、すでにcloseしています。
RaspberryPiセットアップ
https://github.com/KazukoShikiya/RaspPi_PWM_HandsOn/blob/master/RaspberryPi%E3%82%BB%E3%83%83%E3%83%88%E3%82%A2%E3%83%83%E3%83%97に正常インストールの手順が掲載されたため、このインストール方法は非採用となっています。
（非採用理由：B,B+,2で共通手順でインストールできない）

そのため、
ハンズオン環境の構築としてご質問いただいたのであれば、「この手順は利用しないでください」という回答となります。

node-v0.12.7をBにインストールしたいという趣旨でのご質問であれば、node.jsはこちらで作っているものではないので、はお答えしかねます。
nodejshttps://github.com/nodejs/の該当repositoryにあるissueに書き込みをお願いします。
もしくは、stackoverflowへ質問を投げて、この問題を解決している技術者からアドバイスを得るようにしてください。

書き込み、どうもありがとうございました。

**Comment by come25136** [comment]
To @KazukoShikiya 

コメントありがとうございます。
番号の事なのですが、自分の中でsnapshot = スクリーンショット的なもの　と言う解釈があったので
コメントさせていただきました。

node.jsのバージョンのことですがv0.12.7は諦めて他のバージョンをインストールすることによって解決しました。

※GitHubの使い方があまりよく分かっていないので、ここに返信していいのかどうかも迷いつつ返信させてもらいました。

**Comment by KazukoShikiya** [comment]
@homebox25136 返信、ありがとうございます。
（ここに返信で大丈夫です。closeになった件だったので、ちょっとびっくりしただけです。）

snapshotの意味でしたか！納得です。
たしかに日本人からしたら紛らわしい名前のソフトウェアですね。

node.jsのバージョン、なかなか最新が使えるようにならなくて、困りますね。
まぁ、Raspberry Piの趣旨（子供向けの学習用機器）というところからすれば、最新は必要ないという感じではありますが…。

書き込みありがとうございました。
